export const FETCH_MENU_REQUEST = 'FETCH_MENU_REQUEST'
export const FETCH_MENU_SUCCESS = 'FETCH_MENU_SUCCESS'
export const FETCH_MENU_ERROR = 'FETCH_MENU_ERROR'

export const CHECKED_ITEM = 'CHECKED_ITEM'
export const CHECKED_SET_MENU_ITEM = 'CHECKED_SET_MENU_ITEM'
export const CHECKED_CHECKOUT_ITEMS = 'CHECKED_CHECKOUT_ITEMS'

export const ADD_ORDER_REQUEST = 'ADD_ORDER_REQUEST'
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS'
export const ADD_ORDER_ERROR = 'ADD_ORDER_ERROR'

export const DELETE_ORDER_REQUEST = 'DELETE_ORDER_REQUEST'
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS'
export const DELETE_ORDER_ERROR = 'DELETE_ORDER_ERROR'

export const CHECKOUT_ORDER_REQUEST = 'CHECKOUT_ORDER_REQUEST'
export const CHECKOUT_ORDER_SUCCESS = 'CHECKOUT_ORDER_SUCCESS'
export const CHECKOUT_ORDER_ERROR = 'CHECKOUT_ORDER_ERROR'
